### ISSUE TITLE
Combine repositories

### ISSUE THREAD

**Issue by Pyenb** [amirrezaDev1378/ollama-model-direct-download#1]
Hey, I saw your [comment](https://github.com/ollama/ollama/issues/696#issuecomment-2316085177) and it's a good idea. That was also my next plan, to just generate the download links for people directly, as thats also faster than downloading from my Server. But at that time, I didn't know your repo existed. 

What would you say about us just combining this into one single project? Kinda like an suite for ollama models that can be expanded later on. This would also make it more streamlined for users, so that they can choose whatever meets their needs the best.

If you are interested, feel free to reply to me. If this would happen, I think it would be best to do this using an organization, so that it isn't just bound to one single user.

Best regards,
Ben

**Comment by amirrezaDev1378** [comment]
Hi Ben,

I prefer to keep this repository separate, but I have a suggestion for you. If you’d like, I can modify the app to generate download links in a JSON file. You can then add these links to your website so people can download them. Since this is from the Ollama registry, you won’t need to pay anything for hosting.
@Pyenb
